# Generated by Django 3.1.5 on 2021-03-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210323_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
