# Generated by Django 3.1.5 on 2021-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
