# Generated by Django 3.1.5 on 2021-02-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210211_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('-created',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
