# Generated by Django 3.1.5 on 2021-02-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210221_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='friendship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_friendship', to='users.friendship'),
        ),
    ]
